# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Lightsearch Theme"
license = "MIT"
description = "A theme for the lightsearch.uk website based on the Ananke theme"
tags = ["website", "starter", "responsive", "Disqus", "blog", "Tachyons", "Multilingual", "Stackbit"]
features = ["posts", "shortcodes", "related content", "comments"]

[author]
  name = "Chris Platts"
  homepage = "https://virelai.co.uk/"
